development:
 adapter: postgresql
 encoding: unicode
 database: lookingforaCreative_development
 pool: 5
 username: aidabm
 password: aideta7a

test:
 adapter: postgresql
 encoding: unicode
 database: lookingforaCreative_test
 pool: 5
 username: aidabm
 password: aideta7a

# production:
#  database: lookingforaCreative_production
#  username: aidabm
#  password: aideta7a
